---
- name: Set up web server
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    # - letsencrypt
    - nginx

# - name: Set up CONSUL DEMOCRACY
#   hosts: all
#   become: true
#   become_user: "{{ deploy_user }}"
#   vars:
#     # https://github.com/ansible/proposals/issues/89
#     ansible_user: "{{ deploy_user }}"
#   roles:
#     - folder_structure
#     - ruby
#     - rails
#     - email
#     - queue
#     - puma

# - name: Post-installation tasks
#   hosts: all
#   become: true
#   vars:
#     ansible_user: "{{ deploy_user }}"
#   roles:
#     - memcached
#     - timezone

- name: Install Errbit
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - role: mongodb
      when: errbit|bool
    - role: errbit
      become_user: "{{ deploy_user }}"
      when: errbit|bool

# - name: Check system
#   hosts: all
#   become: true
#   vars:
#     ansible_user: "{{ deploy_user }}"
#   roles:
#     - specs
