---
- when: ansible_distribution_release in ["jammy", "noble"] or lookup("env", "CI") != "true"
  block:
    - when: domain is defined
      block:
        - action: uri url=https://{{ server_hostname }} return_content=yes validate_certs=False
          register: webpage_https_with_domain

        - fail:
            msg: "service is not happy {{ webpage_https_with_domain.content }}"
          when: "'CONSUL' not in webpage_https_with_domain.content"

        - name: Redirect to https
          uri:
            url: http://{{ server_hostname }}
            follow_redirects: no
            validate_certs: yes
            status_code: 301

    - when: domain is not defined
      block:
        - action: uri url=http://127.0.0.1 return_content=yes validate_certs=False
          register: webpage_https

        - fail:
            msg: "service is not happy {{ webpage_https.content }}"
          when: "'CONSUL' not in webpage_https.content"

        - name: Do not redirect to https
          uri:
            url: http://{{ server_hostname }}
            follow_redirects: no
            status_code: 200

- name: Get running delayed job processes
  shell: "ps -ef | grep -v grep | grep -w delayed_job | awk '{print $2}'"
  register: delayed_job_process

- fail:
    msg: "Delayed Jobs is not running"
  when: delayed_job_process.stdout == ""
