name: ubuntu
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ubuntu:
    runs-on: ${{ matrix.platforms.os }}
    strategy:
      fail-fast: false
      matrix:
        platforms: [
          { os: "ubuntu-20.04", errbit: "True" },
          { os: "ubuntu-22.04", errbit: "False"}
        ]
        rails_env: [staging, production]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Update system packages
        run: sudo apt-get update -y
      - name: Install OpenSSH
        run: sudo apt-get install -y openssh-server
      - name: Install Ansible
        run: pip3 install ansible
      - name: Create hosts file
        run: echo "localhost ansible_connection=local ansible_user=root" > hosts
      - name: Generate dummy SSH key
        run: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - name: Run CONSUL DEMOCRACY installer
        run: ansible-playbook consul.yml -i hosts --extra-vars "env=${{ matrix.rails_env }} domain=localhost errbit=${{ matrix.platforms.errbit }}"
